In [96]:
import pandas as pd
import numpy as np 

In [97]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [98]:
df = pd.read_csv(
    "/home/abdullah/Downloads/Open_Source/Feature-Engineering/data/covid_toy.csv")

In [99]:
df

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No
...,...,...,...,...,...,...
95,12,Female,104.0,Mild,Bangalore,No
96,51,Female,101.0,Strong,Kolkata,Yes
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No


In [100]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [101]:

df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [102]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [103]:
x_train, x_test , y_train, y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'], test_size=0.2)

## Without Column Transformer

In [104]:
#  adding smiple imputer to fever col 
si = SimpleImputer()
x_train_fever = si.fit_transform(x_train[['fever']])

x_test_fever = si.fit_transform(x_test[['fever']])
x_train_fever.shape


(80, 1)

In [105]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

# also the test data
x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [106]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first', sparse=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender', 'city']])

# also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender', 'city']])

x_train_gender_city.shape

/home/abdullah/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/abdullah/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 4)

In [107]:
x_train_gender_city

array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],


In [108]:
# Extractign age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

In [109]:
x_train_age

array([[49],
       [56],
       [46],
       [19],
       [19],
       [64],
       [60],
       [24],
       [83],
       [24],
       [80],
       [49],
       [34],
       [83],
       [20],
       [25],
       [16],
       [65],
       [60],
       [82],
       [42],
       [71],
       [20],
       [48],
       [80],
       [65],
       [42],
       [23],
       [25],
       [34],
       [54],
       [82],
       [27],
       [47],
       [38],
       [65],
       [51],
       [18],
       [33],
       [69],
       [12],
       [34],
       [22],
       [69],
       [14],
       [10],
       [27],
       [11],
       [79],
       [64],
       [55],
       [82],
       [ 8],
       [12],
       [74],
       [64],
       [ 5],
       [16],
       [23],
       [ 5],
       [73],
       [83],
       [10],
       [38],
       [59],
       [50],
       [75],
       [47],
       [19],
       [27],
       [70],
       [72],
       [73],
       [26],
       [51],
       [51],
       [44],

In [110]:
x_train_age.shape

(80, 1)

In [111]:
print(x_train_age.shape)
print(x_train_fever.shape)
print(x_train_gender_city.shape)
print(x_train_cough.shape)

(80, 1)
(80, 1)
(80, 4)
(80, 1)


In [112]:
X_train_transformed = np.concatenate(
    (x_train_age, x_train_fever, x_train_gender_city, x_train_cough), axis=1)
# also the test data
X_test_transformed = np.concatenate(
    (x_test_age, x_test_fever, x_test_gender_city, x_test_cough), axis=1)

X_train_transformed.shape

(80, 7)

# column Transfermers

In [113]:
from sklearn.compose import ColumnTransformer

In [119]:
transformer = ColumnTransformer(transformers=[
     ('tnf1',SimpleImputer(),['fever']),
     ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
     ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city']),
],remainder='passthrough')

In [120]:
transformer.fit_transform(x_train)

/home/abdullah/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[101.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ,  49.   ],
       [104.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  56.   ],
       [103.   ,   1.   ,   1.   ,   0.   ,   0.   ,   0.   ,  46.   ],
       [101.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ,  19.   ],
       [100.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  19.   ],
       [101.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ,  64.   ],
       [ 99.   ,   0.   ,   0.   ,   0.   ,   0.   ,   1.   ,  60.   ],
       [102.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  24.   ],
       [101.   ,   0.   ,   0.   ,   0.   ,   1.   ,   0.   ,  83.   ],
       [ 98.   ,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,  24.   ],
       [ 98.   ,   0.   ,   0.   ,   1.   ,   0.   ,   0.   ,  80.   ],
       [ 99.   ,   1.   ,   0.   ,   0.   ,   0.   ,   0.   ,  49.   ],
       [100.875,   1.   ,   0.   ,   0.   ,   0.   ,   1.   ,  34.   ],
       [103.   ,   0.   ,   1.   ,   0.   ,   1.   ,   0.   ,  8